apiVersion: v1
kind: Namespace
metadata:
  name: dev
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-nginx-deployment
  namespace: dev
  labels:
    app: a-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a-nginx
  template:
    metadata:
      labels:
        app: a-nginx
    spec:
      containers:
      - name: a-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80