apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-prod
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/reposyncdemo.git
    branch: main
    dir: "/Applications/prod/"
    auth: none