apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-staging
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/reposyncdemo.git
    branch: main
    policyDir: "/Applications/staging/"
    auth: none