apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-nginx
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: c-nginx
  template:
    metadata:
      labels:
        app: c-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.5
        ports:
        - containerPort: 80
